### ISSUE TITLE
Incorrect hours (Time logged)

### ISSUE THREAD

**Issue by Blackbeing** [ayoisaiah/focus#12]
![2023-02-21-121327](https://user-images.githubusercontent.com/112502631/220301114-003e77e4-7363-4d7f-be70-4381475d0994.png)

```
$ focus --version
focus version v1.2.0
https://github.com/ayoisaiah/focus/releases/v1.2.0
```
Focus is built from source

**Comment by ayoisaiah** [comment]
Thank you for reporting this. Can you confirm the commit you built from? I pushed some [related fixes yesterday](https://github.com/ayoisaiah/focus/tree/6ebd013e31fd2b14310f6356c01b4f81ffa11f3b) so I just want to be sure.

**Comment by Blackbeing** [comment]
The problem is still there with latest commit
```
focus --version
focus version v1.3.0
https://github.com/ayoisaiah/focus/releases/v1.3.0
```
![2023-02-22-134222](https://user-images.githubusercontent.com/112502631/220597531-d8d10f24-9bcc-4f63-ac42-baecde090efa.png)

But notice the ALX tag tags correctly. I think large only numbers are affected; unfortunately I'm not familiar with go lang, but in C casting unsigned int to signed int behaves roughly the same.

**Comment by ayoisaiah** [comment]
I'm currently unable to reproduce the issue on my end, but will investigate this further 

![image](https://user-images.githubusercontent.com/13372163/220600945-5c55db5d-6999-4c4e-8044-14d6ea3a3f25.png)

**Comment by Blackbeing** [comment]
could it be my db is corrupted?

**Comment by ayoisaiah** [comment]
I'm unsure of how that could happen, but I'll need to analyze your db file to be sure. Would it be possible for you to send it over?

**Comment by Blackbeing** [comment]
Sure, no problem
[focus.db.zip](https://github.com/ayoisaiah/focus/files/10807454/focus.db.zip)

**Comment by ayoisaiah** [comment]
Thanks!

The problem is that  a couple of abandoned sessions have an invalid end date. I've just pushed a [commit](https://github.com/ayoisaiah/focus/commit/02cb19c7cdffba71c78bc000c1db2701fa94158c) to filter them out.

But I will keep this open till the underlying problem is resolved.
